### ISSUE TITLE
About the number of interactions in the data set

### ISSUE THREAD

**Issue by jiaxingbai** [HKUDS/LLMRec#3]
A good job! Stared! 

However, the number of interactions in the Netflix or Movielens-10m dataset is larger than the dataset you use. How do you filte？

Looking forward to your answer! Thanks!

**Comment by weiwei1206** [comment]
We appreciate your attention to our work. We've made two datasets, Netflix and MovieLens, from scratch, which is why the volume of interaction data in our datasets may differ from the originals. We've put significant effort into data cleaning, resulting in a reduced number of users and items. Furthermore, to ensure a smooth text generation process with large language models, we have imposed limits on the number of users and items. Thank you for your kind attention to our work🤝🤝.
