### ISSUE TITLE
Movielens dataset

### ISSUE THREAD

**Issue by fangyyyyy** [HKUDS/LLMRec#8]
Hi! Your code was using the movielens dataset. And it failed when using the netflix dataset😭. Could you please share the processed movielens data? Thanks in advance! 🙏🙏

**Comment by weiwei1206** [comment]
We appreciate your interest in our work🙏🙏. The Netflix dataset we've released is compatible with running LLMRec and other current baselines such as LATTICE, MICRO, and MMSSL. We processed the dataset ourselves based on the Netflix Prize Data released on the Kaggle website. This processing included organizing the textual data and scraping visual images. Because Netflix is the dataset we processed for the first time, we have released its resources. For MovieLens, we utilized the ml-10m dataset. For more details, please refer to: https://files.grouplens.org/datasets/movielens/ml-10m-README.html

**Comment by fangyyyyy** [comment]
您好！我是张方圆，您的来信我已收到，会尽快查看回复！祝您身体健康，工作顺利，学习愉快！
